# Theta configuration
# chainID: tsub_3610001
genesis:
  hash: "0xe03dd95b4ab38dfe968d2fabc29f536fae3c5d75644ac0a6bac1941d0658ce78"
p2p:
  port: 12100
rpc:
  enabled: true
log:
  #levels: "*:info"
  levels: "*:debug"
consensus:
  minBlockInterval: 3
subchain:
  mainchainEthRpcURL: "http://localhost:18888/rpc"
  subchainEthRpcURL: "http://localhost:19888/rpc"
  chainRegistrarOnMainchain: "0x79EaFd0B5eC8D3f945E6BB2817ed90b046c0d0Af"
  mainchainTFuelTB: "0x5a443704dd4B594B382c22a083e2BD3090A6feF3"
  mainchainTNT20TB: "0xEd8d61f42dC1E56aE992D333A4992C3796b22A74"
  updateInterval: 3000
  #ID: 360777

