# Theta configuration
# chainID: tsub_3610001
genesis:
  hash: "0xb1b7d31d52309bdc4d4d2d8c4b2fb9e79f3fade2e3eca3a8bbf8aedee352e2bf"
p2p:
  port: 12100
rpc:
  enabled: true
log:
  #levels: "*:info"
  levels: "*:debug"
consensus:
  minBlockInterval: 3
subchain:
  mainchainEthRpcURL: "http://localhost:18888/rpc"
  subchainEthRpcURL: "http://localhost:19888/rpc"
  chainRegistrarOnMainchain: "0x560A0c0CA6B0A67895024dae77442C5fd3DC473e"
  mainchainTFuelTB: "0x5a443704dd4B594B382c22a083e2BD3090A6feF3"
  mainchainTNT20TB: "0x57F4B08e0b3CC5a9CBC888639DbE2171B1408722"
  updateInterval: 3000
  #ID: 360777

